export const oolongTeas = [
    {
        id: 1, 
        name: 'Da Hong Pao',
        image: 'dahongpao.jpg',
        description: 'charcoal roasted rock tea from Wuyi Mountain',
        category: 'Yancha',
        price: 35,
    },
    {
        id: 2, 
        name: 'Ali Shan',
        image: 'alishan.jpg',
        description: 'floral lightly oxidized from Ali Mountain in Taiwan',
        category: 'Taiwanese Oolong',
        price: 35,
    },
    {
        id: 3, 
        name: 'Gardenia Frangrence',
        image: 'gardenia.jpg',
        description: 'fruity and floral Phoenix single-bush',
        category: 'Dancong',
        price: 40,
    },
    {
        id: 4, 
        name: 'Orange Blossom Frangrence',
        image: 'orange.jpg',
        description: 'fruity and floral Phoenix single-bush',
        category: 'Dancong',
        price: 45,
    },
    {
        id: 5, 
        name: 'Rou Gui',
        image: 'rougui.jpg',
        description: 'roated spicy cinnamon bark flavor',
        category: 'Yancha',
        price: 25,
    },
    {
        id: 6, 
        name: 'Jin Xuan',
        image: 'jinxuan.jpg',
        description: 'fragrant, smooth and light roasting with a creamy quality',
        category: 'Taiwanese Oolong',
        price: 40,
    },
    {
        id: 7, 
        name: 'Tieguanyin',
        image: 'tieguanyin.jpg',
        description: 'roasted grain gives way to a delicious brothiness, both in flavour and in mouthfeel, followed by verdant notes',
        category: 'Rolled Oolong',
        price: 27,
    },

];